[workspace]
pr_branch_prefix = "release/candidate-"    # PR branch prefix
pr_name = "Release agentai v{{ version }}" # template for the PR name
pr_labels = ["release"]                    # add the `release` label to the release Pull Request
pr_draft = false
git_release_draft = false

# Currently we are in alpha state of development
semver_check = false

[changelog]
header = """# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.1.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]
"""

body = """

## [{{ version }}]\
    {%- if release_link -%}\
        ({{ release_link }})\
    {% endif %} \
    - {{ timestamp | date(format="%Y-%m-%d") }}
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group | upper_first }}
    {% for commit in commits %}
        {%- if commit.scope -%}
            - *({{commit.scope}})* {% if commit.breaking %}[**breaking**] {% endif %}\
                {{ commit.message }}{{ self::username(commit=commit) }}\
                {%- if commit.links %} \
                    ({% for link in commit.links %}[{{link.text}}]({{link.href}}) {% endfor -%})\
                {% endif %}
        {% else -%}
            - {% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message }}{{ self::username(commit=commit) }}{{ self::pr(commit=commit) }}
        {% endif -%}
    {% endfor -%}
{% endfor %}
{%- if remote.contributors %}
### Contributors
{% for contributor in remote.contributors %}
    * @{{ contributor.username }}
{%- endfor %}
{% endif -%}
{%- macro username(commit) -%}
    {% if commit.remote.username %} (by @{{ commit.remote.username }}){% endif -%}
{% endmacro -%}
{%- macro pr(commit) -%}
    {% if commit.remote.pr_number %} - #{{ commit.remote.pr_number }}{% endif -%}
{% endmacro -%}
"""

commit_parsers = [
    { message = "^[Ff]eat", group = "1. New features" },     # Use this section when adding new functionality or peforming bigger change to it
    { message = "^[Cc]hanged", group = "2. Changed" },       # Use this section when performing some "smaller" change to other "module"
    { message = "^[Ff]ix", group = "3. Fixes" },             # Use this section when fixing reported issues
    { message = "^[Dd]eprecated", group = "4. Deprecated" }, # Use this section for items that will be or was removed
    { message = "^.*", group = "9. Miscellaneous" },         # Miscellanous items like chore, documentation update etc.
]

[[package]]
name = "agentai"
version_group = "agentai"

[[package]]
name = "agentai-macros"
version_group = "agentai"
